-- AlterTable
ALTER TABLE "wallet" ADD COLUMN     "locked" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN     "totalBet" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN     "totalWin" DECIMAL(65,30) NOT NULL DEFAULT 0;
